### ISSUE TITLE
Editing the menu links

### ISSUE THREAD

**Issue by lkhrs** [stackbithq/stackbit-theme-fresh#1]
Good morning! Love the work ya'll are doing at Stackbit.

I've encountered an issue with this theme and editing the left-side menu, I can't seem to add more links and I cannot find the file where they're supposed to be added. From my limited understanding, Header.js is supposed to check either a file or a set of files in a folder (I'm brand-new to React, still figuring stuff out) and return a set of list elements for each item. 
There's also gatsby-plugin-menus in the gatsby-config.js which points to a "./src/data/menus.json" which is an empty file.

Through Forestry.io, I added a new page which shows up under src/pages but doesn't seem to be added to the left-hand menu.

Any help would be appreciated in solving this :)

Thank you!

**Comment by lkhrs** [comment]
Actually this seems to be more of an issue with Forestry than the theme, my bad.

After comparing the about.md file, it's clear I needed to have some menu config in the top part:

menus:
  main:
    title: 
    weight: 4

The Forestry setup doesn't seem to automatically add that when creating a new page.

**Comment by lkhrs** [comment]
![image](https://user-images.githubusercontent.com/1342461/62415988-73c02580-b5f8-11e9-890e-44a722f673b1.png)
I resolved this by adding the appropriate fields to my frontmatter.

**Comment by smnh** [comment]
@lkhrs Forestry has build in menus management only for sites powered by Jekyll and Hugo.
For Gatsby sites, as you have noted, you need to edit the frontmatter of each page and manually add the needed fields to the `menus` object. If you want to add global menu items not related to any page, you can do it through the menus.json, which should be available as a separate collection item in Forestry.
